<h3>Review Completeness</h3>
<p>Review that all parts of the document exists and that each part actually contains what it should</p>
<ul>
<li>Test Strategy 
	<ul>
		<li>Does the strategy describe stakeholders and their testing goals?</li>
		<li>Does the strategy describe the available resources?</li>
		<li>Does the strategy describe how the stakeholders testing goals are to be fulfilled by the plan?</li>
	</ul>
</li>

<li>Test Plan - Should describe and outline the current iteration's test effort(Who does what when). 
	<ul>
		<li>Does the test-plan describe what requirements that should be tested?</li>
		<li>Does the test-plan describe what requirements that should NOT be tested?</li>
		<li>Does the test-plan describe how testing should be done? at what test-level?</li>
		<li>Does the test-plan describe who should do different activities? (responsibilities)</li>
	</ul>
</li>

<li>Manual Test Cases
	<ul>
		<li>Are the manual test-cases traceable to which requirement that is tested?</li>
		<li>Do each manual test-case describe, input and expected output? (when relevant)</li>
	</ul>
</li>

<li>Test Report
	<ul>
		<li>Does the test-plan show what has been tested and not tested?</li>
		<li>Does the test-report show which tests that fail or succeed?</li>
		<li>Is there testing the other group should have done?</li>
	</ul>
</li>
</ul>


<p>Comment on what was missing. Comment on what could be removed or simplified.</p>
