<h3>Review Content</h3>

<p>Review the test effort by the other group. Has the other group done a good job reporting their testing of the product?</p>


Ambition and test-effort
<ul>
	<li>Has the other group done a good job testing of the product, given the resources?</li>
	<li>Do the manual test-cases cover all relevant scenarios in the use-cases?</li>
	<li>Do the test-effort cover the relevant requirements?</li>
</ul>

<p>Comment on what parts you think was good, what parts that could be improved and how to improve them:</p>





