<ul>
<li>A good review should be truthful (correct)</li>
<li>A good review should helpful give clues to what is good and what is not and suggest changes.</li>
<li>A good review should be thorough and complete</li>
<li>A good review may still be of a different oppinion than yours.</li>
</ul>

A bad grade does not automatically mean that you or the reviewer gets a low grade, it is an indication of that something is not right.
If you think something is wrong with the review, state your view in the comments. Be polite. You are anonymous to the other student but not to the teaching assistants.

Remember different people have different views and may interpret the same information differently. Learn from this, how could you have written your document in a way that this reviewer would have liked?


<p>Comment on what you learned from this review also motivate your grading of this review. </p>
