<?php

return array("-1" => "Not graded yet",	
		"0" => "0. Not even an attempt - The review has no comments and grading is wrong.",
		"1" => "1. Failed - Most of the review is not correct and fail to motivate the grading.",
		"2" => "2. Sufficient - The review is truthful and motivates grading but the text is sparse, or the review does not seem thourough.",
		"3" => "3. Good - The review is truthful and motivates the grading in a good way. A proper review!",
		"4" => "4. Excellent - The review is truthful, thourough and motivates the grading in a good way. Also the review was helpful and I learned how to write better artifacts(strategy/plan/cases/report) from it");