<ul>
  <li>The strategy, test-plan, test-cases and test-report should be written as a single MarkDown formatted (.md) file</li>
  <li>The document should be anonymous, no names or traces of who you are should be in the document. Instead use role-names like “test-lead”, “scrum-master” or “product-owner”. The document and other text are not anonymous to course management.</li>
  <li>All students in the group should upload the exact same document, please make sure that if you update the document and resubmit that all students update it.</li>
  <li>The document or parts of it may not be shared between groups.</li>
  <li>Read the review task in order to find out more about how to write a successful document.</li>
  <li>If you are more than one student in your group every student must upload the exact same file.</li>
</ul>
