<h3>Review Clarity</h3>
<p>Review the ease of which the document can be read and understood.</p>

<ul>
<li>Language - Should be English. Issues can be related to Spelling or Grammar</li>
<li>Format and layout - The document uses Markdown. It uses Tables, Links, Titles of different levels when appropriate</li>
<li>Disposition - The order of chapters or sections follow naturally in way that they can be read from top to the bottom. The chapters are divided into paragraphs of text with a title.</li>
</ul>

<p>Comment on what was clear, and not clear, and give the student a strategy to improve their clarity.</p>